// DO NOT EDIT THIS FILE
enableSaving [false,false];
setGroupIconsVisible [true,false]; //Show only 2D
enableCamShake true;
setViewDistance 2000;
setTerrainGrid 25;


// clients
if (!isDedicated) then {

	{ _x setMarkerAlphaLocal 0; } foreach ["respawn_west","respawn_east","respawn_guer","respawn_guerrila","respawn_civilian","area"];

	// hide all area markers for UPS
	for "_i" from 0 to 50 do {
		_a = format ["area%1",_i];
		_a setMarkerAlphaLocal 0;
		_a = format ["area_%1",_i];
		_a setMarkerAlphaLocal 0;
	};

	// Add teleport options to tlag
	if (!isNil "fp_flag") then {
		[fp_flag,[["Alpha Actual","a0"],["Bravo Actual","b0"],["Charlie Actual","c0"],["Delta Actual","d0"]]] call compile preProcessFileLineNumbers "src\teleport.sqf";
	};
	
	[] spawn {
		waitUntil {!isNull player};

		// respawn with gear if using template gear
		player addEventHandler ["Respawn",{
			_this execVM "src\respawn.sqf";
			// Time before the teleport flag (if available) can be used again, to prevent people from just teleporting after dying.
			// The flag is for JiPs not deaths. 3 min default
			FP_timeout = time + 180;
		}];

		// so player never joins "ENEMY" side.
		player addEventHandler ["HandleRating", {
			_rating = _this select 1;
			(abs _rating)
		}];

		// deletes grenades thrown in spawn
		player addEventHandler ["Fired",
		{
			if (_this select 2 == "HandGrenadeMuzzle") then
			{
				if ((_this select 0) distance (markerPos (["respawn_west","respawn_east","respawn_guerrila","respawn_civilian"] select ([WEST,EAST,independent,civilian] find side player))) < 50) then
				{
					deleteVehicle (_this select 6);
					titleText ["G IS FOR GRENADES", "PLAIN", 3];
				};
			};
		}];

		sleep  0.3;
		// lower weapon
		player switchMove "amovpercmstpslowwrfldnon";
		if (leader group player == player) then {
			_cnt  = count units group player;
			if (_cnt <= 2 || {_cnt mod 2 != 0}) exitWith{};
			_a = []; _b = [];
			{_x assignTeam (if (_forEachIndex < _cnt/2) then {"BLUE"}else{"RED"})}foreach units group player;
		};

		// respawn with correct loadout if using template loadout
		_timeOut = time + 15;
		waitUntil {(player getVariable ["FP_kit_type", ""] != "") || time > _timeOut};
		FP_kit_type = player getVariable ["FP_kit_type", ""];
	};
};

// server
if (isServer) then 
{
	createCenter west;
	createCenter east;
	createCenter resistance;
	createCenter civilian;
	
	{
		_x addCuratorEditableObjects [vehicles,true];
		_x addCuratorEditableObjects [(allMissionObjects "Man"),false];
		_x addCuratorEditableObjects [(allMissionObjects "Air"),true];
		_x addCuratorEditableObjects [(allMissionObjects "Ammo"),false];
	}forEach allCurators;

	FP_addCuratorObject = {
		_add = if (typeName _this != typeName []) then {[_this]}else{_this};
		{
			_x addCuratorEditableObjects [_add,  true];
		} foreach allCurators;
	};
};